name: windows

on: push

jobs:
  llvm:
    strategy:
      matrix:
        arch: ["32", "64"]
        version: ["18.1.8"]
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: false
      - name: prepare llvm
        run: |
          pip install packaging
          python get_llvm_ps1.py ${{ matrix.version }} ${{ matrix.arch }}
          ./get_llvm_${{ matrix.version }}_${{ matrix.arch }}.ps1
      - name: publish llvm to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_name: xmake-mirror/llvm-windows
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: clang+llvm-${{ matrix.version }}-win${{ matrix.arch }}.zip
          asset_name: clang+llvm-${{ matrix.version }}-win${{ matrix.arch }}.zip
          tag: "${{ matrix.version }}"
          body: "llvm for windows ${{ matrix.version }}"
